/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenii_p2_joedsosa;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joeds
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.pack(); 
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void llenarTree(Deporte depo) {
        DefaultMutableTreeNode dep1 = new DefaultMutableTreeNode(depo);
        DefaultMutableTreeNode dep2 = new DefaultMutableTreeNode(depo);
        DefaultMutableTreeNode dep3 = new DefaultMutableTreeNode(depo);
        DefaultMutableTreeNode dep4 = new DefaultMutableTreeNode(depo);
        ((DefaultMutableTreeNode) root.getChildAt(0)).add(dep1);
        ((DefaultMutableTreeNode) root.getChildAt(1)).add(dep2);
        ((DefaultMutableTreeNode) root.getChildAt(2)).add(dep3);
        ((DefaultMutableTreeNode) root.getChildAt(3)).add(dep4);

        for (Torneo torneo : depo.getTorneos()) {
            if (torneo.getPeriodo().equals("Q1")) {
                dep1.add(new DefaultMutableTreeNode(torneo));
            }
            if (torneo.getPeriodo().equals("Q2")) {
                dep2.add(new DefaultMutableTreeNode(torneo));
            }
            if (torneo.getPeriodo().equals("Q4")) {
                dep3.add(new DefaultMutableTreeNode(torneo));
            }
            if (torneo.getPeriodo().equals("Q5")) {
                dep4.add(new DefaultMutableTreeNode(torneo));
            }
        }
        model.reload();
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_listar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jb_volver = new javax.swing.JButton();
        pop_quarters = new javax.swing.JPopupMenu();
        agregar_item = new javax.swing.JMenuItem();
        upload = new javax.swing.JMenuItem();
        pop_deportes = new javax.swing.JPopupMenu();
        crear_item = new javax.swing.JMenuItem();
        guardar_item = new javax.swing.JMenuItem();
        pop_torneos = new javax.swing.JPopupMenu();
        agregarequip_item = new javax.swing.JMenuItem();
        pop_team = new javax.swing.JPopupMenu();
        create_mi = new javax.swing.JMenuItem();
        jd_simulacion = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_equipo1 = new javax.swing.JComboBox<>();
        cb_equipo2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        js_equipo1 = new javax.swing.JSpinner();
        js_equipo2 = new javax.swing.JSpinner();
        jb_guardarresul = new javax.swing.JButton();
        jb_volver1 = new javax.swing.JButton();
        jd_tabla = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jb_listar = new javax.swing.JButton();
        jp_pro = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        jd_listar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_listarWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jList1.setBackground(new java.awt.Color(255, 102, 102));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new DefaultListModel()
        );
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LISTA DE EQUIPOS");

        jb_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenii_p2_joedsosa/iconocvolver.png"))); // NOI18N
        jb_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        agregar_item.setText("Agregar Deporte\n");
        agregar_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_itemActionPerformed(evt);
            }
        });
        pop_quarters.add(agregar_item);

        upload.setText("Upload\n");
        upload.setContentAreaFilled(false);
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        pop_quarters.add(upload);

        crear_item.setText("Crear Torneo\n");
        crear_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_itemActionPerformed(evt);
            }
        });
        pop_deportes.add(crear_item);

        guardar_item.setText("Save\n");
        guardar_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_itemActionPerformed(evt);
            }
        });
        pop_deportes.add(guardar_item);

        agregarequip_item.setText("Añadir Equipo\n");
        agregarequip_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarequip_itemActionPerformed(evt);
            }
        });
        pop_torneos.add(agregarequip_item);

        create_mi.setText("Agregar Equipo");
        create_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_miActionPerformed(evt);
            }
        });
        pop_team.add(create_mi);

        jd_simulacion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_simulacionWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SIMULACION DE PARTIDO");

        cb_equipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_equipo1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VS");

        jb_guardarresul.setText("GUARDAR");
        jb_guardarresul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarresulActionPerformed(evt);
            }
        });

        jb_volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenii_p2_joedsosa/iconocvolver.png"))); // NOI18N
        jb_volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_volver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jb_guardarresul))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_volver1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_volver1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(js_equipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_guardarresul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        jTable1.setBackground(new java.awt.Color(255, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipo", "GA", "GC ", "PTS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_tablaLayout = new javax.swing.GroupLayout(jd_tabla.getContentPane());
        jd_tabla.getContentPane().setLayout(jd_tablaLayout);
        jd_tablaLayout.setHorizontalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tablaLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_tablaLayout.setVerticalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tablaLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jTree2.setBackground(new java.awt.Color(255, 102, 102));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNITEC");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTRACION DE TORNEOS");

        jb_listar.setText("Listar Equipos");
        jb_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listarActionPerformed(evt);
            }
        });

        jButton1.setText("Simulacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jp_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_listar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseClicked
        // TODO add your handling code here:

        model = (DefaultTreeModel) jTree2.getModel();
        root = (DefaultMutableTreeNode) model.getRoot();
        int row = jTree2.getClosestRowForLocation(evt.getX(), evt.getY());
        jTree2.setSelectionRow(row);
        Object v1 = jTree2.getSelectionPath().getLastPathComponent();
        node = (DefaultMutableTreeNode) v1;
        if (evt.isMetaDown()) {
            if (node.getUserObject().equals("Torneos")) {
                pop_team.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (node.getUserObject() instanceof String) {
                pop_quarters.show(evt.getComponent(), evt.getX(), evt.getY());
            }

            if (node.getUserObject() instanceof Deporte deporte) {
                deportes = deporte;
                pop_deportes.show(evt.getComponent(), evt.getX(), evt.getY());
            }
            if (node.getUserObject() instanceof Torneo torneo) {
                torneos = torneo;
                pop_torneos.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }

    }//GEN-LAST:event_jTree2MouseClicked

    private void agregar_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_itemActionPerformed
        // TODO add your handling code here:

        Deporte deporte = new Deporte(JOptionPane.showInputDialog("Nombre del Deporte:"));
        model = (DefaultTreeModel) jTree2.getModel();
        root = (DefaultMutableTreeNode) model.getRoot();
        for (int i = 0; i < 4; i++) {
            ((DefaultMutableTreeNode) root.getChildAt(i)).add(new DefaultMutableTreeNode(deporte));
        }
        model.reload();
        jTree2.setModel(model);

    }//GEN-LAST:event_agregar_itemActionPerformed

    private void create_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_miActionPerformed
        // TODO add your handling code here:
        equipos.add(new Equipo(JOptionPane.showInputDialog("Nombre del equipo")));
        
    }//GEN-LAST:event_create_miActionPerformed

    private void crear_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_itemActionPerformed
        // TODO add your handling code here:
        Torneo tourney = new Torneo(JOptionPane.showInputDialog("Ingrese el nombre: "), node.getParent().toString());
        deportes.addTorneo(tourney);
        node.add(new DefaultMutableTreeNode(tourney));
        model.reload();


    }//GEN-LAST:event_crear_itemActionPerformed

    private void guardar_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_itemActionPerformed
        // TODO add your handling code here:
        Save(deportes);
    }//GEN-LAST:event_guardar_itemActionPerformed

    private void agregarequip_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarequip_itemActionPerformed
       
    String pinga = "";
        for (Equipo equi : equipos) {
            pinga += equipos.indexOf(equi) + ") " + equi + "\n";
        }
        int index = Integer.parseInt(JOptionPane.showInputDialog("Ingrese equipo\n" + pinga));
        if (!torneos.getEquipos().contains(equipos.get(index))) {
            torneos.equiposagg(equipos.get(index));
            
        } else {
            JOptionPane.showMessageDialog(this, "NOT FOUND");
        }

    }//GEN-LAST:event_agregarequip_itemActionPerformed

    private void jb_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jd_listar.setVisible(true);
        jd_listar.pack();
        jd_listar.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_listarActionPerformed

    private void jb_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_volverActionPerformed
        // TODO add your handling code here:
        jd_listar.setVisible(false);
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_volverActionPerformed

    private void cb_equipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_equipo1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_cb_equipo1ActionPerformed

    private void jb_guardarresulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarresulActionPerformed
        // TODO add your handling code here:
        if (cb_equipo1.getSelectedItem().equals(cb_equipo2.getSelectedItem())) {
            JOptionPane.showMessageDialog(this, "NO PUEDE SER EL MISMO EQUIPO!!");
        } else {
            Equipo team = ((Equipo) cb_equipo1.getSelectedItem());
            Equipo scnteam= ((Equipo) cb_equipo2.getSelectedItem());
            if ((int) js_equipo1.getValue() > (int) js_equipo2.getValue()) {
                team.contpunt(3);
            } else {
                scnteam.contpunt(3);
            }
            if ((int) js_equipo1.getValue() == (int) js_equipo2.getValue()) {
                team.contpunt(1);
                scnteam.contpunt(1);
            }
            Partido partido = new Partido();
            Equipo[] e = {team, scnteam};
            partido.setEquipos(e);
            Integer[] r = {(int) js_equipo1.getValue(), (int) js_equipo2.getValue()};
            partido.setResultados(r);
            team.addPartido(partido);
            scnteam.addPartido(partido);
            JOptionPane.showMessageDialog(this, "GANO EL MEJOR");
        }
    }//GEN-LAST:event_jb_guardarresulActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
         if (jList1.getSelectedIndex() >= 0) {
            DefaultListModel model = (DefaultListModel) jList1.getModel();
            Equipo equipo = ((Equipo) model.getElementAt(jList1.getSelectedIndex()));
            DefaultTableModel modell = (DefaultTableModel) jTable1.getModel();
            modell.setRowCount(0);
            for (Partido partido : equipo.getPartido()) {
                String[] pp = {partido.getEquipos()[0].toString(), partido.getEquipos()[1].toString(), partido.getResultados()[0].toString() + " ## " + partido.getResultados()[1].toString()};
                modell.addRow(pp);
            }
            modell.fireTableDataChanged();

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jd_listarWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_listarWindowOpened
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jList1.getModel();
        modelo.clear();
        for (Equipo equipo : torneos.getEquipos()) {
            modelo.addElement(equipo);
        }
        jList1.setModel(modelo);
    }//GEN-LAST:event_jd_listarWindowOpened

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        File file = null;
        FileInputStream fis = null;
        ObjectInputStream ois = null;
       
        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Nuila te amo", "cathy");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                file = jfc.getSelectedFile();
                fis = new FileInputStream(file);
                ois = new ObjectInputStream(fis);
                Deporte dep = (Deporte) ois.readObject();
                for (Torneo torneo : dep.getTorneos()) {
                    ArrayList<Equipo> es = torneo.getEquipos();
                    for (Equipo equip : es) {
                        if (!equipos.contains(equip)) {
                            equipos.add(equip);
                        }
                    }
                }
                llenarTree(dep);
            } 

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            ois.close();
            fis.close();
        } catch (IOException ex) {
        }

                                          
    }//GEN-LAST:event_uploadActionPerformed

    private void jd_simulacionWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_simulacionWindowOpened
        // TODO add your handling code here:
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_equipo1.getModel();
        model.removeAllElements();
        model.addAll(torneos.getEquipos());
        cb_equipo1.setModel(model);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_equipo2.getModel();
        modelo.removeAllElements();
        modelo.addAll(torneos.getEquipos());
        cb_equipo2.setModel(modelo);
    }//GEN-LAST:event_jd_simulacionWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jd_simulacion.setVisible(true);
        jd_simulacion.pack();
        jd_simulacion.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_volver1ActionPerformed
        // TODO add your handling code here:
        jd_simulacion.setVisible(false);
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_volver1ActionPerformed
    static ArrayList<Equipo> equipos = new ArrayList();
    static DefaultMutableTreeNode node;
    static Deporte deportes;
    static Torneo torneos;
    static Equipo equipo;
    static DefaultTreeModel model;
    static DefaultMutableTreeNode root;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void Save(Deporte sport) {
        JFileChooser jfc = new JFileChooser("./");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Torneo docs", "cathy");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);

        FileOutputStream fo = null;
        ObjectOutputStream oo = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                File fichero = null;
                fichero = new File(jfc.getSelectedFile().getPath() + ".cathy");

                fo = new FileOutputStream(fichero);
                oo = new ObjectOutputStream(fo);
                oo.writeObject(sport);
                oo.flush();
                ProgressBarThread p = new ProgressBarThread(jp_pro, sport);
                p.start();

            } catch (Exception e) {
                e.printStackTrace();
            }

        }//fin IF
        try {
            fo.close();
            oo.close();
            
        } catch (IOException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregar_item;
    private javax.swing.JMenuItem agregarequip_item;
    private javax.swing.JComboBox<String> cb_equipo1;
    private javax.swing.JComboBox<String> cb_equipo2;
    private javax.swing.JMenuItem crear_item;
    private javax.swing.JMenuItem create_mi;
    private javax.swing.JMenuItem guardar_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree2;
    private javax.swing.JButton jb_guardarresul;
    private javax.swing.JButton jb_listar;
    private javax.swing.JButton jb_volver;
    private javax.swing.JButton jb_volver1;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JDialog jd_tabla;
    private javax.swing.JProgressBar jp_pro;
    private javax.swing.JSpinner js_equipo1;
    private javax.swing.JSpinner js_equipo2;
    private javax.swing.JPopupMenu pop_deportes;
    private javax.swing.JPopupMenu pop_quarters;
    private javax.swing.JPopupMenu pop_team;
    private javax.swing.JPopupMenu pop_torneos;
    private javax.swing.JMenuItem upload;
    // End of variables declaration//GEN-END:variables

}
